language: java

jdk:
  - openjdk9

addons:
  sonarcloud:
    organization: "AstronomVM"
    token:
      secure: 6ad459a4157f9e9ca2dccaa07671774e10c6fc71
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -P TRAVIS_BUILD
  - HEROKU_API_KEY="c463c02d-86e7-45fa-ac34-30f3ba3c4eb9" mvn heroku:deploy
